version: 2
updates:
  # Frontend dependencies (Next.js, React, TypeScript, etc.)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    assignees:
      - "ryosuke-horie"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "chore"
      include: "scope"
    target-branch: "main"
    vendor: false
    versioning-strategy: "increase"

  # API dependencies (Hono, Drizzle, TypeScript, etc.)
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "10:00"
      timezone: "Asia/Tokyo"
    assignees:
      - "ryosuke-horie"
    labels:
      - "dependencies"
      - "api"
    commit-message:
      prefix: "chore"
      include: "scope"
    target-branch: "main"
    vendor: false
    versioning-strategy: "increase"

  # GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "11:00"
      timezone: "Asia/Tokyo"
    assignees:
      - "ryosuke-horie"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "ci"
      include: "scope"
    target-branch: "main"