name: Frontend CI (Self-hosted)

on:
  # プルリクエストで自動実行
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'frontend/**'
      - '!frontend/**/*.md'
      - '!frontend/docs/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/frontend-ci.yml'
  # mainブランチへのpushは引き続き自動実行
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '!frontend/**/*.md'
      - '!frontend/docs/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/frontend-ci.yml'
  # 手動トリガー（デバッグ用に残す）
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request number'
        required: false
        type: string

# GitHub Actions無料枠節約のため、同一PRで複数実行時は前の実行をキャンセル
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-checks:
    name: Frontend Quality Checks
    runs-on: self-hosted
    timeout-minutes: 15
    
    permissions:
      contents: read
    
    defaults:
      run:
        working-directory: frontend
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22'
          # セルフホストランナーの制約によりキャッシュは無効
          # cache: 'pnpm'
          # cache-dependency-path: frontend/pnpm-lock.yaml
      
      - name: Clean pnpm setup directory
        run: |
          # pnpm/action-setupのデフォルトディレクトリをクリーンアップ
          rm -rf ~/setup-pnpm || true
          rm -rf /home/runner-user/setup-pnpm || true
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.12.1
      
      - name: Install dependencies
        run: |
          # セルフホストランナー用に一時的なストアディレクトリを使用
          export PNPM_STORE_DIR="/tmp/pnpm-store-${{ github.run_id }}"
          # キャッシュを使用しない設定
          echo "store-dir=$PNPM_STORE_DIR" > ~/.npmrc
          echo "prefer-offline=false" >> ~/.npmrc
          # 依存関係のインストール
          pnpm install --frozen-lockfile --prefer-offline false
          # インストール後にストアをクリーンアップ
          rm -rf "$PNPM_STORE_DIR" || true
          rm -f ~/.npmrc || true
      
      - name: Type check
        run: pnpm run typecheck
      
      - name: Biome lint and format check
        run: pnpm run lint:biome
      
      - name: Unit tests
        run: pnpm run test:unit
        
      - name: Build check
        run: pnpm run build
