name: Frontend CI (Self-hosted)

on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

# GitHub Actions無料枠節約のため、同一PRで複数実行時は前の実行をキャンセル
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-checks:
    name: Frontend Quality Checks
    runs-on: self-hosted
    timeout-minutes: 15
    
    defaults:
      run:
        working-directory: frontend
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22'
          # セルフホストランナーの制約によりキャッシュは無効
          # cache: 'npm'
          # cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Type check
        run: npm run typecheck
      
      - name: Biome lint and format check
        run: npm run lint:biome
      
      - name: Unit tests with coverage
        run: npm run test:unit:coverage
        
      - name: Vitest Coverage Report
        uses: davelosert/vitest-coverage-report-action@v2
        if: always()
        with:
          json-summary-path: './frontend/coverage/coverage-summary.json'
          json-final-path: './frontend/coverage/coverage-final.json'
          vite-config-path: './frontend/vitest.config.ts'
          github-token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build check
        run: npm run build
